spring:
  application:
    name: parking
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/parkingdb}
    username: ${SPRING_DATASOURCE_USERNAME:parkinguser}
    password: ${SPRING_DATASOURCE_PASSWORD:parkingpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql